---
- name: Update
  become: yes
  apt:
    update_cache: yes
    upgrade: no

- name: Install pip
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"

- name: Add gcloud GPG apt Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add gcloud repository
  apt_repository:
    repo: deb https://packages.cloud.google.com/apt cloud-sdk main
    state: present

- name: Add Kubernetes GPG apt Key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Add kubernetes repository
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Install pip
  become: yes
  apt:
    name: kubectl
    state: present

- name: Install pip dependencies for ansible
  pip:
    name: ansible
    state: latest
    extra_args: --user

- name: Install Ansible
  become: yes
  apt:
    name: ansible
    state: present

- name: Install pip dependencies for gcloud
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pip_dependencies }}"

- name: Install cli
  become: yes
  apt:
    name: google-cloud-cli
    state: present

- name: Install auth-plugin
  become: yes
  apt:
    name: google-cloud-sdk-gke-gcloud-auth-plugin
    state: present
